// Central project database for SkyEagle Studio
window.projectsData = [
  {
    slug: "al-noor-solar-energy",
    name: "Al-Noor Solar Energy",
    industry: "Solar Energy",
    type: "Business Website",
    description: "Business portal presenting sustainable solar setups, client catalogs, calculators, and system savings trackers.",
    technologies: ["HTML5", "CSS3", "JavaScript", "PHP"],
    liveUrl: "https://al-noorsolarenergy.com/#home",
    imageUrl: "images/solar_mockup.jpg",
    category: "Websites"
  },
  {
    slug: "zm-solar-electric",
    name: "ZM Solar Electric",
    industry: "Solar Energy",
    type: "Electrical Business",
    description: "Clean, high-performance solar solution showcase page featuring quote requests and installation case studies.",
    technologies: ["HTML5", "CSS3", "JavaScript"],
    liveUrl: "https://zmsolarelectric.com/",
    imageUrl: "images/solar_mockup.jpg",
    category: "Websites"
  },
  {
    slug: "bin-zareen",
    name: "Bin Zareen",
    industry: "Solar Energy",
    type: "Business / Corporate Website",
    description: "A premium green technology website promoting solar hardware options, customized installations, and savings graphs.",
    technologies: ["HTML5", "CSS3", "JavaScript"],
    liveUrl: "https://binzareen.com/",
    imageUrl: "images/solar_mockup.jpg",
    category: "Websites"
  },
  {
    slug: "al-fazal-hospital",
    name: "Al-Fazal Hospital",
    industry: "Healthcare",
    type: "Hospital Website",
    description: "Comprehensive hospital site with appointment reservation forms, staff lists, department lists, and clinical reviews.",
    technologies: ["HTML5", "CSS3", "JavaScript", "Node.js"],
    liveUrl: "https://www.al-fazalhospital.com/",
    imageUrl: "images/medical_mockup.jpg",
    category: "Healthcare"
  },
  {
    slug: "doorskill",
    name: "DoorSkill",
    industry: "Education",
    type: "Skills / Business",
    description: "Educational and skills development platform designed to empower learners with practical business skills and professional courses.",
    technologies: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
    liveUrl: "https://www.doorskill.com/",
    imageUrl: "images/solar_mockup.jpg",
    category: "Websites"
  },
  {
    slug: "best-hair-lahore",
    name: "Best Hair Lahore",
    industry: "Beauty / Hair",
    type: "Business Website",
    description: "Premium clinical portal for hair restoration and medical aesthetics, featuring appointment scheduling and before/after treatment catalogs.",
    technologies: ["HTML5", "CSS3", "JavaScript"],
    liveUrl: "https://www.besthairlahore.com/",
    imageUrl: "images/medical_mockup.jpg",
    category: "Websites"
  },
  {
    slug: "zepiva",
    name: "Zepiva",
    industry: "Business / E-Commerce",
    type: "Brand Website",
    description: "E-commerce brand store built with responsive checkout flows, modular product collections, and modern storefront styling.",
    technologies: ["Next.js", "Tailwind CSS", "TypeScript", "Node.js"],
    liveUrl: "https://www.zepiva.com/",
    imageUrl: "images/ecommerce_mockup.jpg",
    category: "E-Commerce"
  },
  {
    slug: "dental-clinics-management-software",
    name: "Dental Clinic Management Software",
    industry: "Healthcare Software",
    type: "SaaS / Desktop / Web / Mobile",
    description: "Advanced dental management system built with appointment schedulers, treatment logs, billing invoices, and doctor profiles. Configurable for online/offline deployment.",
    technologies: ["Next.js", "TypeScript", "Firebase", "Tailwind CSS"],
    liveUrl: "https://dental-clinics-software.vercel.app/",
    imageUrl: "images/software_mockup.jpg",
    category: "Software"
  },
  {
    slug: "lumora-dental",
    name: "Lumora Dental",
    industry: "Healthcare",
    type: "Dental Portal",
    description: "High-aesthetic dentistry portal showcasing treatments, clinic portfolios, and dynamic scheduling screens.",
    technologies: ["HTML5", "CSS3", "JavaScript"],
    liveUrl: "https://toprmrproducer.github.io/lumora-dental/about.html",
    imageUrl: "images/medical_mockup.jpg",
    category: "Websites"
  },
  {
    slug: "autoelite-showroom",
    name: "AutoElite Showroom",
    industry: "Automotive",
    type: "Premium Catalog",
    description: "Futuristic premium car showcase directory displaying high-definition specs, videos, and dynamic inquiry models.",
    technologies: ["HTML5", "CSS3", "JavaScript"],
    liveUrl: "https://muhammadumairamir12-del.github.io/Autoelite/",
    mockupBorderColor: "#ff00f7",
    mockupIcon: "fa-tachometer-alt",
    mockupSubtitle: "Premium Catalog",
    category: "Websites"
  },
  {
    slug: "cars-web-portal",
    name: "Cars Web Portal",
    industry: "Automotive",
    type: "Rental Layout",
    description: "High-performance responsive landing interface constructed for booking rental fleets and vehicle detailing bookings.",
    technologies: ["HTML5", "CSS3", "JavaScript"],
    liveUrl: "https://muhammadumairamir12-del.github.io/cars-web/",
    mockupBorderColor: "#00f0ff",
    mockupIcon: "fa-road",
    mockupSubtitle: "Rental Layout",
    category: "Websites"
  },
  {
    slug: "bikes-web",
    name: "Bikes Web",
    industry: "Automotive",
    type: "Motorcycle Portal",
    description: "Modern single-page site outlining sport bikes specifications, price comparisons, and dealership information.",
    technologies: ["HTML5", "CSS3", "JavaScript"],
    liveUrl: "https://muhammadumairamir12-del.github.io/bikes-web/",
    mockupBorderColor: "#00ff66",
    mockupIcon: "fa-motorcycle",
    mockupSubtitle: "Motorcycle Portal",
    category: "Websites"
  },
  {
    slug: "muslim-gym-portal",
    name: "Muslim Gym Portal",
    industry: "Gym & Fitness",
    type: "Fitness Center",
    description: "Responsive health club site containing subscription pricing plans, training schedules, and muscle gain tracking forms.",
    technologies: ["HTML5", "CSS3", "JavaScript"],
    liveUrl: "https://muhammadumairamir12-del.github.io/Muslim-Gym/",
    mockupBorderColor: "#ff5500",
    mockupIcon: "fa-dumbbell",
    mockupSubtitle: "Fitness Center",
    category: "Websites"
  },
  {
    slug: "tahir-traders-agriculture",
    name: "Tahir Traders Agriculture",
    industry: "Agriculture",
    type: "Agri Trading",
    description: "Wholesale trading catalog featuring local crops, seeds, high-grade fertilizers, and agricultural equipment.",
    technologies: ["HTML5", "CSS3", "JavaScript"],
    liveUrl: "https://muhammadumairamir12-del.github.io/tahir-traders/",
    mockupBorderColor: "#a3ff00",
    mockupIcon: "fa-leaf",
    mockupSubtitle: "Agri Trading",
    category: "Websites"
  },
  {
    slug: "naeem-jd-sofa-web",
    name: "Naeem Jd Sofa Web",
    industry: "Sofa & Decor",
    type: "Luxury Furniture",
    description: "Visual showroom web presentation outlining customized wooden sofas, office furniture, and house decor elements.",
    technologies: ["HTML5", "CSS3", "JavaScript"],
    liveUrl: "https://muhammadumairamir12-del.github.io/Naeem-Jd/",
    mockupBorderColor: "#d2a679",
    mockupIcon: "fa-couch",
    mockupSubtitle: "Luxury Furniture",
    category: "Websites"
  },
  {
    slug: "world-teach",
    name: "World Teach",
    industry: "Tech & Learning",
    type: "Education Portal",
    description: "Interactive technology tutorial index, online course database, and digital classroom dashboard.",
    technologies: ["HTML5", "CSS3", "JavaScript"],
    liveUrl: "https://muhammadumairamir12-del.github.io/world-teach/#",
    mockupBorderColor: "#ffd700",
    mockupIcon: "fa-laptop-code",
    mockupSubtitle: "Education Portal",
    category: "Websites"
  },
  {
    slug: "real-estate-web",
    name: "Real Estate Web",
    industry: "Real Estate",
    type: "Property Brokerage",
    description: "Modern real estate listings directory showing housing schemes, residential plots, commercial properties, and inquiry forms.",
    technologies: ["HTML5", "CSS3", "JavaScript"],
    liveUrl: "https://muhammadumairamir12-del.github.io/Real-Esatate/",
    mockupBorderColor: "#00f0ff",
    mockupIcon: "fa-building",
    mockupSubtitle: "Property Brokerage",
    category: "Real Estate"
  },
  {
    slug: "salons-aesthetics-web",
    name: "Salons & Aesthetics Web",
    industry: "Beauty & Spa",
    type: "Salons & Aesthetics",
    description: "Aesthetic beauty salon website featuring hair styling catalogs, makeup pricing indices, and booking forms.",
    technologies: ["HTML5", "CSS3", "JavaScript"],
    liveUrl: "https://muhammadumairamir12-del.github.io/salons-web/",
    mockupBorderColor: "#ff00f7",
    mockupIcon: "fa-cut",
    mockupSubtitle: "Beauty & Spa",
    category: "Websites"
  },
  {
    slug: "karyana-store-portal",
    name: "Karyana Store Portal",
    industry: "Retail & Grocery",
    type: "E-Commerce Store",
    description: "E-commerce grocery store dashboard built for managing stock categories, pricing, sales receipts, and delivery orders.",
    technologies: ["HTML5", "CSS3", "JavaScript"],
    liveUrl: "https://muhammadumairamir12-del.github.io/-umair-bhi/",
    imageUrl: "images/ecommerce_mockup.jpg",
    category: "E-Commerce"
  },
  {
    slug: "custom-billing-pos-software",
    name: "Custom Billing & POS Software",
    industry: "Custom Software",
    type: "SaaS / Retail / POS",
    description: "Industrial Point of Sale (POS) and inventory tracker software designed for pharmacies, bakeries, clothing, and retail markets.",
    technologies: ["C#", ".NET", "MySQL"],
    liveUrl: "contact.html?interest=pos",
    imageUrl: "images/software_mockup.jpg",
    category: "Software"
  },
  {
    slug: "premium-graphic-posters",
    name: "Premium Graphic Posters & Flyers",
    industry: "Graphic Designs",
    type: "Branding & Art",
    description: "High-conversion commercial graphic designs, social media branding kits, banners, and advertising prints constructed for digital marketing campaigns.",
    technologies: ["Photoshop", "Illustrator"],
    liveUrl: "contact.html?interest=graphics",
    mockupBorderColor: "#ff00f7",
    mockupIcon: "fa-palette",
    mockupSubtitle: "Posters & Banners",
    category: "Business"
  }
];
